# Generated by Django 5.0.6 on 2024-05-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_alter_customermodel_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='nationality',
            field=models.CharField(choices=[('I', 'INDIA'), ('C', 'CHINA'), ('U', 'USA')], max_length=1),
        ),
    ]
